services:

  application:
    container_name: pokedex-application
    profiles:
      - 'dev'
    build:
      context: .
      dockerfile: docker/Dockerfile-application
    image: luanvn4/pokedex:1.0
    ports:
      - "8090:8080"

  tests:
    container_name: pokedex-tests
    profiles:
      - 'test'
    build:
      context: .
      dockerfile: docker/Dockerfile-tests
    image: luanvn4/pokedex-tests:1.0


