CREATE TABLE IF NOT EXISTS pokemons (
    id INT GENERATED ALWAYS AS IDENTITY,
    nome VARCHAR(50) NOT NULL,
    descricao VARCHAR(250) NOT NULL,
    altura DECIMAL NOT NULL,
    peso DECIMAL NOT NULL
);