FROM maven:3.9.9 AS build

WORKDIR /app

COPY ../pom.xml /app/pom.xml

# Baixando as dependências previamente, é possível aproveitar o cache do docker
# Ele só irá baixar elas novamente se o pom.xml for alterado
RUN mvn dependency:go-offline

COPY ../src /app/src

RUN mvn clean package


FROM tomcat:11 AS deploy

# Documentação sobre anotações de metadados presente em:
# https://github.com/opencontainers/image-spec/blob/main/annotations.md
LABEL org.opencontainers.image.authors="luanvilaca1@gmail.com" \
      org.opencontainers.image.description="Imagem contendo uma aplicação web de uma pokedex utilizando servlets"

ENV CATALINA_HOME=/usr/local/tomcat

COPY --from=build /app/src/main/resources/db/init.sql /app/src/main/resources/db/V1__init.sql
COPY --from=build /app/target/pokedex.war $CATALINA_HOME/webapps/pokedex.war

RUN mv webapps.dist/* webapps/ && \
    rmdir webapps.dist

EXPOSE 8080

CMD ["catalina.sh", "run"]
