name: Continuous Integration (CI)

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-package: 'jdk'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B install -Dskiptests
      - name: Test with Maven
        run: mvn -B test